-- ==============================================================================
-- V12__create_ai_shield_policy_configs_table.sql
-- Table and Initial Seed for Dynamic AI Shield Policy Configurations
-- ==============================================================================

CREATE TABLE IF NOT EXISTS ai_shield_policy_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier VARCHAR(50) UNIQUE NOT NULL,
    label VARCHAR(100) NOT NULL,
    min_score NUMERIC(5, 2) NOT NULL,
    max_score NUMERIC(5, 2) NOT NULL,
    description TEXT,
    action_type VARCHAR(50) DEFAULT 'MANUAL_REVIEW',
    is_active BOOLEAN DEFAULT TRUE,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ai_shield_policy_tier ON ai_shield_policy_configs(tier);
CREATE INDEX IF NOT EXISTS idx_ai_shield_policy_active ON ai_shield_policy_configs(is_active);

-- Seed initial default policies for AI Shield moderation tiers
INSERT INTO ai_shield_policy_configs (tier, label, min_score, max_score, description, action_type, is_active, display_order)
VALUES
(
    'RED_ALERT',
    'Báo động đỏ',
    0.00,
    50.00,
    'Điểm dưới 50% - Báo động đỏ, nội dung vi phạm hoặc sai lệch sử liệu nghiêm trọng',
    'MANUAL_REVIEW',
    TRUE,
    1
),
(
    'FAIR',
    'Khá',
    50.00,
    80.00,
    'Điểm từ 50% đến dưới 80% - Khá, cần rà soát và hoàn thiện thêm',
    'MANUAL_REVIEW',
    TRUE,
    2
),
(
    'GOOD',
    'Tốt',
    80.00,
    90.00,
    'Điểm từ 80% đến 90% - Tốt, đạt chuẩn xuất bản',
    'MANUAL_REVIEW',
    TRUE,
    3
),
(
    'EXCELLENT',
    'Xuất sắc',
    90.00,
    100.00,
    'Điểm trên 90% - Xuất sắc, chất lượng tư liệu rất cao',
    'MANUAL_REVIEW',
    TRUE,
    4
)
ON CONFLICT (tier) DO NOTHING;
