-- ==============================================================================
-- V13__expand_user_roles_many_to_many_and_add_freelancer.sql
-- Expand user-role relation to Many-to-Many and add FREELANCER role & profile
-- ==============================================================================

-- 1. Insert FREELANCER role if not exists
INSERT INTO roles (name, description)
SELECT 'FREELANCER', 'Freelancer role for taking jobs, submitting proposals and deliverables'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'FREELANCER');

-- 2. Create user_roles junction table for Many-to-Many relationship
CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    assigned_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id)
);

CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role_id ON user_roles(role_id);

-- 3. Backfill existing user role relationships from users.role_id
INSERT INTO user_roles (user_id, role_id, assigned_at)
SELECT id, role_id, COALESCE(created_at, CURRENT_TIMESTAMP)
FROM users
WHERE role_id IS NOT NULL
ON CONFLICT (user_id, role_id) DO NOTHING;

-- 4. Create freelancer_profiles table for freelancer bio, portfolio, and skills
CREATE TABLE IF NOT EXISTS freelancer_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    headline VARCHAR(255),
    bio TEXT,
    skills TEXT,
    portfolio_url VARCHAR(1000),
    status VARCHAR(50) DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_freelancer_profiles_user_id ON freelancer_profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_freelancer_profiles_status ON freelancer_profiles(status);
