-- ==============================================================================
-- V14__creator_freelancer_booking_escrow_system.sql
-- Schema for Creator - Freelancer Booking, Milestone Contracts & Escrow System
-- ==============================================================================

-- 1. Update freelancer_profiles with service_types, voice_demo_url, reference_price
ALTER TABLE freelancer_profiles
    ADD COLUMN IF NOT EXISTS service_types VARCHAR(255),
    ADD COLUMN IF NOT EXISTS voice_demo_url VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS reference_price NUMERIC(15, 2);

-- 2. Ensure bank_accounts has verified status
ALTER TABLE bank_accounts
    ADD COLUMN IF NOT EXISTS verified_at TIMESTAMP WITH TIME ZONE;

-- 3. Create posts table (BOOKING by Creator, JOB_SEEKING by Freelancer)
CREATE TABLE IF NOT EXISTS posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL, -- BOOKING | JOB_SEEKING
    service_type VARCHAR(50) NOT NULL, -- CONTENT | VOICE
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    reference_price NUMERIC(15, 2),
    status VARCHAR(50) NOT NULL DEFAULT 'OPEN', -- OPEN | IN_CONTRACT | CLOSED | EXPIRED | HIDDEN
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_posts_user_id ON posts(user_id);
CREATE INDEX IF NOT EXISTS idx_posts_type_status ON posts(type, status);
CREATE INDEX IF NOT EXISTS idx_posts_service_type ON posts(service_type);

-- 4. Create applications table (Freelancer applies to Creator's BOOKING post)
CREATE TABLE IF NOT EXISTS applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    applicant_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message TEXT,
    proposed_price NUMERIC(15, 2),
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING', -- PENDING | CHOSEN | REJECTED
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_post_applicant UNIQUE (post_id, applicant_id)
);

CREATE INDEX IF NOT EXISTS idx_applications_post_id ON applications(post_id);
CREATE INDEX IF NOT EXISTS idx_applications_applicant_id ON applications(applicant_id);

-- 5. Upgrade contracts table to support Booking & Milestone flow
ALTER TABLE contracts
    ADD COLUMN IF NOT EXISTS post_id BIGINT REFERENCES posts(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS creator_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    ADD COLUMN IF NOT EXISTS freelancer_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    ADD COLUMN IF NOT EXISTS service_type VARCHAR(50),
    ADD COLUMN IF NOT EXISTS title VARCHAR(255),
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS total_amount NUMERIC(15, 2),
    ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS accept_due_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_contracts_creator_id ON contracts(creator_id);
CREATE INDEX IF NOT EXISTS idx_contracts_freelancer_id ON contracts(freelancer_id);
CREATE INDEX IF NOT EXISTS idx_contracts_status ON contracts(status);

-- 6. Create milestones table
CREATE TABLE IF NOT EXISTS milestones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL REFERENCES contracts(id) ON DELETE CASCADE,
    order_no INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    requirement TEXT NOT NULL,
    amount NUMERIC(15, 2) NOT NULL,
    duration_days INT NOT NULL,
    max_revisions INT NOT NULL DEFAULT 2,
    revisions_used INT NOT NULL DEFAULT 0,
    status VARCHAR(50) NOT NULL DEFAULT 'WAITING', -- WAITING | UNFUNDED | IN_PROGRESS | SUBMITTED | APPROVED | RELEASED | DISPUTED | CANCELLED
    fund_due_at TIMESTAMP WITH TIME ZONE,
    due_at TIMESTAMP WITH TIME ZONE,
    review_due_at TIMESTAMP WITH TIME ZONE,
    release_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_milestones_contract_id ON milestones(contract_id);
CREATE INDEX IF NOT EXISTS idx_milestones_status ON milestones(status);

-- 7. Create submissions table (Freelancer submits work for milestone)
CREATE TABLE IF NOT EXISTS submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    milestone_id BIGINT NOT NULL REFERENCES milestones(id) ON DELETE CASCADE,
    version_no INT NOT NULL,
    content TEXT,
    file_url VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_submissions_milestone_id ON submissions(milestone_id);

-- 8. Create revision_requests table (Creator requests changes)
CREATE TABLE IF NOT EXISTS revision_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    milestone_id BIGINT NOT NULL REFERENCES milestones(id) ON DELETE CASCADE,
    submission_id BIGINT REFERENCES submissions(id) ON DELETE SET NULL,
    note TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_revision_requests_milestone ON revision_requests(milestone_id);

-- 9. Create escrow_payments table (Escrow per milestone)
CREATE TABLE IF NOT EXISTS escrow_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    milestone_id BIGINT NOT NULL UNIQUE REFERENCES milestones(id) ON DELETE CASCADE,
    amount NUMERIC(15, 2) NOT NULL,
    platform_fee NUMERIC(15, 2) DEFAULT 0,
    net_amount NUMERIC(15, 2) DEFAULT 0,
    status VARCHAR(50) NOT NULL DEFAULT 'HELD', -- HELD | RELEASED | REFUNDED | FROZEN
    funded_at TIMESTAMP WITH TIME ZONE,
    released_at TIMESTAMP WITH TIME ZONE,
    refunded_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_escrow_payments_status ON escrow_payments(status);

-- 10. Upgrade disputes table
ALTER TABLE disputes
    ADD COLUMN IF NOT EXISTS milestone_id BIGINT REFERENCES milestones(id) ON DELETE CASCADE,
    ADD COLUMN IF NOT EXISTS evidence TEXT,
    ADD COLUMN IF NOT EXISTS counter_evidence TEXT,
    ADD COLUMN IF NOT EXISTS result VARCHAR(50), -- RELEASE_TO_FREELANCER | REFUND_TO_CREATOR | SPLIT
    ADD COLUMN IF NOT EXISTS split_percent NUMERIC(5, 2),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_disputes_milestone_id ON disputes(milestone_id);

-- 11. Create reviews table (Ratings & comments upon contract completion)
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL REFERENCES contracts(id) ON DELETE CASCADE,
    reviewer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reviewee_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_contract_reviewer UNIQUE (contract_id, reviewer_id)
);

CREATE INDEX IF NOT EXISTS idx_reviews_contract_id ON reviews(contract_id);
CREATE INDEX IF NOT EXISTS idx_reviews_reviewee_id ON reviews(reviewee_id);
