-- ==============================================================================
-- V15__create_booking_escrow_configs_table.sql
-- Table and default seed data for dynamic Admin Booking & Escrow configuration
-- ==============================================================================

CREATE TABLE IF NOT EXISTS booking_escrow_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(100) NOT NULL UNIQUE,
    config_value VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_booking_escrow_configs_key ON booking_escrow_configs(config_key);

-- Seed default values
INSERT INTO booking_escrow_configs (config_key, config_value, description)
VALUES
    ('CONTRACT_ACCEPT_HOURS', '48', 'Thời hạn Freelancer phản hồi hợp đồng (giờ)'),
    ('FUND_HOURS', '48', 'Thời hạn Creator ký quỹ cho milestone (giờ)'),
    ('FUND_PAUSE_MAX_DAYS', '7', 'Thời gian tạm dừng tối đa trước khi hủy hợp đồng (ngày)'),
    ('REVIEW_DAYS', '3', 'Thời hạn Creator duyệt sản phẩm (ngày)'),
    ('RELEASE_HOLD_DAYS', '3', 'Thời gian giữ tiền sau duyệt trước khi giải ngân (ngày)'),
    ('REVISION_DAYS', '2', 'Thời hạn Freelancer chỉnh sửa sản phẩm (ngày)'),
    ('MAX_MILESTONES', '5', 'Số milestone tối đa trong 1 hợp đồng'),
    ('MAX_REVISIONS_DEFAULT', '2', 'Số lượt yêu cầu chỉnh sửa mặc định mỗi milestone'),
    ('PLATFORM_FEE_PERCENT', '5.0', 'Tỉ lệ phí nền tảng khấu trừ (%)'),
    ('JOB_INTERVAL_MINUTES', '60', 'Chu kỳ chạy job quét hạn (phút)')
ON CONFLICT (config_key) DO NOTHING;
