-- ==============================================================================
-- V16__create_livestream_sessions_table.sql
-- Schema for Livestream Sessions (Agora RTC)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS livestream_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    creator_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    thumbnail_url VARCHAR(1000),
    agora_channel_name VARCHAR(100) NOT NULL UNIQUE,
    is_exclusive BOOLEAN DEFAULT FALSE,
    status VARCHAR(50) NOT NULL DEFAULT 'LIVE',
    viewer_count INT DEFAULT 0,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_livestreams_channel_id ON livestream_sessions(channel_id);
CREATE INDEX IF NOT EXISTS idx_livestreams_creator_id ON livestream_sessions(creator_id);
CREATE INDEX IF NOT EXISTS idx_livestreams_status ON livestream_sessions(status);
