-- ==============================================================================
-- V18__create_milestone_deliverables_table.sql
-- Table for Milestone Deliverables (giai đoạn sản phẩm đầu ra, bảo mật & liên kết với bài post)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS milestone_deliverables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    milestone_id BIGINT NOT NULL REFERENCES milestones(id) ON DELETE CASCADE,
    post_id BIGINT REFERENCES posts(id) ON DELETE SET NULL,
    submission_id BIGINT REFERENCES submissions(id) ON DELETE SET NULL,
    uploaded_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(1000) NOT NULL,
    file_size BIGINT,
    content_type VARCHAR(100),
    version_no INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_milestone_deliverables_milestone_id ON milestone_deliverables(milestone_id);
CREATE INDEX IF NOT EXISTS idx_milestone_deliverables_post_id ON milestone_deliverables(post_id);
CREATE INDEX IF NOT EXISTS idx_milestone_deliverables_uploaded_by ON milestone_deliverables(uploaded_by);
