-- ==============================================================================
-- V19__create_milestone_reviews_table.sql
-- Table for Milestone Reviews (Đánh giá chất lượng theo từng giai đoạn Milestone)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS milestone_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    milestone_id BIGINT NOT NULL REFERENCES milestones(id) ON DELETE CASCADE,
    contract_id BIGINT NOT NULL REFERENCES contracts(id) ON DELETE CASCADE,
    reviewer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reviewee_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_milestone_reviewer UNIQUE (milestone_id, reviewer_id)
);

CREATE INDEX IF NOT EXISTS idx_milestone_reviews_milestone_id ON milestone_reviews(milestone_id);
CREATE INDEX IF NOT EXISTS idx_milestone_reviews_contract_id ON milestone_reviews(contract_id);
CREATE INDEX IF NOT EXISTS idx_milestone_reviews_reviewee_id ON milestone_reviews(reviewee_id);
