-- ==============================================================================
-- V1__init_schema.sql
-- Initial Schema for PRM Monolith Platform (27 Tables)
-- ==============================================================================

-- 1. ROLES
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description TEXT
);

-- 2. USERS
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT REFERENCES roles(id),
    email VARCHAR(255),
    phone VARCHAR(255),
    password_hash VARCHAR(255),
    status VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE
);

-- 3. KYC PROFILES
CREATE TABLE IF NOT EXISTS kyc_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    phone VARCHAR(255),
    otp_code VARCHAR(255),
    otp_verified_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE
);

-- 4. REFRESH TOKENS
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    token VARCHAR(255),
    issued_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    revoked BOOLEAN,
    revoked_at TIMESTAMP WITH TIME ZONE
);

-- 5. CHANNELS
CREATE TABLE IF NOT EXISTS channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id BIGINT REFERENCES users(id),
    name VARCHAR(255),
    description TEXT,
    avatar_url VARCHAR(255),
    cover_url VARCHAR(255),
    status VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE
);

-- 6. CONTENTS
CREATE TABLE IF NOT EXISTS contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT REFERENCES channels(id),
    title VARCHAR(255),
    text_body TEXT,
    source_type VARCHAR(255),
    status VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);

-- 7. ARTIFACTS
CREATE TABLE IF NOT EXISTS artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id BIGINT REFERENCES contents(id),
    type VARCHAR(255),
    file_url VARCHAR(255),
    source_type VARCHAR(255),
    duration_seconds INTEGER,
    status VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE
);

-- 8. TRANSCRIPTS
CREATE TABLE IF NOT EXISTS transcripts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_id BIGINT REFERENCES artifacts(id),
    text_body TEXT,
    created_at TIMESTAMP WITH TIME ZONE
);

-- 9. AI FILTER LOGS
CREATE TABLE IF NOT EXISTS ai_filter_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_id BIGINT REFERENCES artifacts(id),
    result VARCHAR(255),
    score NUMERIC(38,2),
    reason TEXT,
    checked_at TIMESTAMP WITH TIME ZONE
);

-- 10. MODERATION REVIEWS
CREATE TABLE IF NOT EXISTS moderation_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_id BIGINT REFERENCES artifacts(id),
    moderator_id BIGINT REFERENCES users(id),
    decision VARCHAR(255),
    reason TEXT,
    escalated BOOLEAN,
    reviewed_at TIMESTAMP WITH TIME ZONE
);

-- 11. COMMENTS
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_id BIGINT REFERENCES artifacts(id),
    user_id BIGINT REFERENCES users(id),
    parent_comment_id BIGINT REFERENCES comments(id),
    text_body TEXT,
    status VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE
);

-- 12. REACTIONS
CREATE TABLE IF NOT EXISTS reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_id BIGINT REFERENCES artifacts(id),
    user_id BIGINT REFERENCES users(id),
    type VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE
);

-- 13. MEMBERSHIPS
CREATE TABLE IF NOT EXISTS memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viewer_id BIGINT REFERENCES users(id),
    channel_id BIGINT REFERENCES channels(id),
    status VARCHAR(255),
    started_at TIMESTAMP WITH TIME ZONE,
    ended_at TIMESTAMP WITH TIME ZONE
);

-- 14. MEMBERSHIP PAYMENTS
CREATE TABLE IF NOT EXISTS membership_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_id BIGINT REFERENCES memberships(id),
    amount NUMERIC(38,2),
    commission_amount NUMERIC(38,2),
    creator_earning NUMERIC(38,2),
    status VARCHAR(255),
    paid_at TIMESTAMP WITH TIME ZONE
);

-- 15. WALLETS
CREATE TABLE IF NOT EXISTS wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    available_balance NUMERIC(38,2),
    pending_balance NUMERIC(38,2),
    currency VARCHAR(255),
    updated_at TIMESTAMP WITH TIME ZONE
);

-- 16. WALLET TRANSACTIONS
CREATE TABLE IF NOT EXISTS wallet_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT REFERENCES wallets(id),
    type VARCHAR(255),
    amount NUMERIC(38,2),
    related_type VARCHAR(255),
    related_id BIGINT,
    status VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE
);

-- 17. BANK ACCOUNTS
CREATE TABLE IF NOT EXISTS bank_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    bank_name VARCHAR(255),
    account_number VARCHAR(255),
    account_holder_name VARCHAR(255),
    verified BOOLEAN,
    created_at TIMESTAMP WITH TIME ZONE
);

-- 18. WITHDRAWALS
CREATE TABLE IF NOT EXISTS withdrawals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT REFERENCES wallets(id),
    bank_account_id BIGINT REFERENCES bank_accounts(id),
    amount NUMERIC(38,2),
    status VARCHAR(255),
    requested_at TIMESTAMP WITH TIME ZONE,
    processed_at TIMESTAMP WITH TIME ZONE,
    failure_reason TEXT
);

-- 19. NARRATOR PROFILES
CREATE TABLE IF NOT EXISTS narrator_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    bio TEXT,
    languages VARCHAR(255),
    base_rate NUMERIC(38,2),
    status VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE
);

-- 20. NARRATOR DEMOS
CREATE TABLE IF NOT EXISTS narrator_demos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    narrator_profile_id BIGINT REFERENCES narrator_profiles(id),
    title VARCHAR(255),
    file_url VARCHAR(255),
    uploaded_at TIMESTAMP WITH TIME ZONE
);

-- 21. HIRE REQUESTS
CREATE TABLE IF NOT EXISTS hire_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id BIGINT REFERENCES users(id),
    narrator_id BIGINT REFERENCES users(id),
    channel_id BIGINT REFERENCES channels(id),
    description TEXT,
    proposed_price NUMERIC(38,2),
    deadline DATE,
    status VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE
);

-- 22. CONTRACTS
CREATE TABLE IF NOT EXISTS contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hire_request_id BIGINT REFERENCES hire_requests(id),
    terms_text TEXT,
    price NUMERIC(38,2),
    deadline DATE,
    status VARCHAR(255),
    creator_signed_at TIMESTAMP WITH TIME ZONE,
    narrator_signed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE
);

-- 23. ESCROW TRANSACTIONS
CREATE TABLE IF NOT EXISTS escrow_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT REFERENCES contracts(id),
    amount NUMERIC(38,2),
    commission_amount NUMERIC(38,2),
    status VARCHAR(255),
    locked_at TIMESTAMP WITH TIME ZONE,
    released_at TIMESTAMP WITH TIME ZONE
);

-- 24. DELIVERABLES
CREATE TABLE IF NOT EXISTS deliverables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT REFERENCES contracts(id),
    file_url VARCHAR(255),
    status VARCHAR(255),
    review_note TEXT,
    submitted_at TIMESTAMP WITH TIME ZONE,
    reviewed_at TIMESTAMP WITH TIME ZONE
);

-- 25. DISPUTES
CREATE TABLE IF NOT EXISTS disputes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT REFERENCES contracts(id),
    raised_by BIGINT REFERENCES users(id),
    reason TEXT,
    status VARCHAR(255),
    resolved_by BIGINT REFERENCES users(id),
    resolution TEXT,
    resolved_at TIMESTAMP WITH TIME ZONE
);

-- 26. AUDIT LOGS
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT REFERENCES users(id),
    action_type VARCHAR(255),
    target_type VARCHAR(255),
    target_id BIGINT,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE
);

-- 27. SYSTEM CONFIGS
CREATE TABLE IF NOT EXISTS system_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(255),
    value TEXT,
    updated_by BIGINT REFERENCES users(id),
    updated_at TIMESTAMP WITH TIME ZONE
);

-- ==============================================================================
-- INDEXES FOR PERFORMANCE
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_token ON refresh_tokens(token);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_channels_creator_id ON channels(creator_id);
CREATE INDEX IF NOT EXISTS idx_contents_channel_id ON contents(channel_id);
CREATE INDEX IF NOT EXISTS idx_artifacts_content_id ON artifacts(content_id);
CREATE INDEX IF NOT EXISTS idx_comments_artifact_id ON comments(artifact_id);
CREATE INDEX IF NOT EXISTS idx_reactions_artifact_id ON reactions(artifact_id);
CREATE INDEX IF NOT EXISTS idx_memberships_viewer_id ON memberships(viewer_id);
CREATE INDEX IF NOT EXISTS idx_memberships_channel_id ON memberships(channel_id);
CREATE INDEX IF NOT EXISTS idx_wallets_user_id ON wallets(user_id);
CREATE INDEX IF NOT EXISTS idx_wallet_tx_wallet_id ON wallet_transactions(wallet_id);
CREATE INDEX IF NOT EXISTS idx_contracts_hire_request ON contracts(hire_request_id);
CREATE INDEX IF NOT EXISTS idx_hire_requests_creator ON hire_requests(creator_id);
CREATE INDEX IF NOT EXISTS idx_hire_requests_narrator ON hire_requests(narrator_id);
