-- ==============================================================================
-- V22__create_series_and_series_items_tables.sql
-- Tạo bảng series và series_items cho phép Creator quản lý tuyển tập Podcast / Video
-- ==============================================================================

CREATE TABLE IF NOT EXISTS series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    cover_url VARCHAR(1000),
    status VARCHAR(50) NOT NULL DEFAULT 'PUBLISHED', -- PUBLISHED | HIDDEN | DRAFT
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_series_channel_id ON series(channel_id);
CREATE INDEX IF NOT EXISTS idx_series_status ON series(status);

CREATE TABLE IF NOT EXISTS series_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id BIGINT NOT NULL REFERENCES series(id) ON DELETE CASCADE,
    content_id BIGINT NOT NULL REFERENCES contents(id) ON DELETE CASCADE,
    order_no INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_series_content UNIQUE (series_id, content_id)
);

CREATE INDEX IF NOT EXISTS idx_series_items_series_id ON series_items(series_id);
CREATE INDEX IF NOT EXISTS idx_series_items_content_id ON series_items(content_id);
CREATE INDEX IF NOT EXISTS idx_series_items_order ON series_items(series_id, order_no);
