-- ==============================================================================
-- V4__enhance_payment_and_membership.sql
-- Enhancement for Payment, Wallet and Channel Membership Domains
-- ==============================================================================

-- 1. Bảng gói hội viên của kênh (Mỗi kênh 1 gói mặc định)
CREATE TABLE IF NOT EXISTS channel_membership_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    monthly_price NUMERIC(38,2) NOT NULL CHECK (monthly_price >= 0),
    perks JSONB NOT NULL DEFAULT '[]'::jsonb,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_channel_default_membership_plan UNIQUE (channel_id)
);

-- 2. Bổ sung plan_id vào bảng memberships
ALTER TABLE memberships
    ADD COLUMN IF NOT EXISTS plan_id BIGINT REFERENCES channel_membership_plans(id),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

-- 3. Bổ sung các trường định danh VNPay vào wallet_transactions
ALTER TABLE wallet_transactions
    ADD COLUMN IF NOT EXISTS merchant_txn_ref VARCHAR(100),
    ADD COLUMN IF NOT EXISTS gateway_txn_no VARCHAR(100),
    ADD COLUMN IF NOT EXISTS gateway_provider VARCHAR(50) DEFAULT 'INTERNAL',
    ADD COLUMN IF NOT EXISTS description TEXT;

-- 4. Bổ sung cờ nội dung độc quyền vào contents
ALTER TABLE contents
    ADD COLUMN IF NOT EXISTS is_exclusive BOOLEAN DEFAULT FALSE;

-- 5. Constraints & Indexes bảo vệ nghiệp vụ
-- Chống trùng lặp mã giao dịch nạp tiền
CREATE UNIQUE INDEX IF NOT EXISTS uq_wallet_tx_merchant_ref 
ON wallet_transactions(merchant_txn_ref);

-- Chống 1 viewer có 2 gói ACTIVE cùng lúc cho 1 kênh
CREATE UNIQUE INDEX IF NOT EXISTS uq_active_membership_per_channel 
ON memberships(viewer_id, channel_id) 
WHERE status = 'ACTIVE';

-- Chống 1 creator tạo nhiều yêu cầu rút tiền đang chờ xử lý đồng thời
CREATE UNIQUE INDEX IF NOT EXISTS uq_creator_pending_withdrawal 
ON withdrawals(wallet_id) 
WHERE status IN ('PENDING', 'PROCESSING');
