-- ==============================================================================
-- V5__add_creator_ai_settings.sql
-- Table to store Creator's personal AI Settings (Gemini Key, ElevenLabs Key, Voice)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS creator_ai_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    gemini_api_key VARCHAR(255),
    elevenlabs_api_key VARCHAR(255),
    tts_engine VARCHAR(50) DEFAULT 'edge-tts',
    voice_name VARCHAR(100) DEFAULT 'vi-VN-NamMinhNeural',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_creator_ai_settings_user_id ON creator_ai_settings(user_id);
