-- ==============================================================================
-- V9__create_email_templates_table.sql
-- Table and Initial Seed for Dynamic Email Templates
-- ==============================================================================

CREATE TABLE IF NOT EXISTS email_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    html_content TEXT NOT NULL,
    description TEXT,
    status VARCHAR(50) DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_email_templates_code ON email_templates(code);
CREATE INDEX IF NOT EXISTS idx_email_templates_status ON email_templates(status);

-- Seed initial templates so HTML is stored in DB instead of hardcoded in Java
INSERT INTO email_templates (code, name, subject, html_content, description, status)
VALUES
(
    'FORGOT_PASSWORD_OTP',
    'Mã OTP Đặt Lại Mật Khẩu',
    '[History Podcast] Mã OTP đặt lại mật khẩu tài khoản',
    '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e0e0e0; border-radius: 8px;">
    <h2 style="color: #8b0000; margin-bottom: 16px;">Yêu Cầu Đặt Lại Mật Khẩu</h2>
    <p>Xin chào bạn,</p>
    <p>Hệ thống nhận được yêu cầu đặt lại mật khẩu cho tài khoản <strong>History Podcast</strong> liên kết với email này.</p>
    <p>Mã xác thực OTP của bạn là:</p>
    <div style="text-align: center; margin: 24px 0;">
        <span style="font-size: 32px; font-weight: bold; letter-spacing: 6px; color: #8b0000; background-color: #fdf2f2; border: 1px solid #fecaca; padding: 12px 24px; border-radius: 6px; display: inline-block;">{{otpCode}}</span>
    </div>
    <p style="color: #666; font-size: 14px;">Mã xác thực này có hiệu lực trong <strong>{{expiryMinutes}} phút</strong>. Tuyệt đối không chia sẻ mã này cho bất kỳ ai khác.</p>
    <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;" />
    <p style="color: #999; font-size: 12px;">Nếu bạn không thực hiện yêu cầu này, vui lòng bỏ qua email để đảm bảo an toàn cho tài khoản của bạn.</p>
</div>',
    'Mẫu email gửi mã OTP khi người dùng yêu cầu đặt lại mật khẩu',
    'ACTIVE'
),
(
    'CREATOR_KYC_OTP',
    'Mã OTP Xác Thực Creator',
    '[History Podcast] Mã xác thực OTP đăng ký Nhà Sáng Tạo (Creator)',
    '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e0e0e0; border-radius: 8px;">
    <h2 style="color: #8b0000; margin-bottom: 16px;">Xác Thực Hồ Sơ Creator</h2>
    <p>Xin chào bạn,</p>
    <p>Bạn đang thực hiện quy trình đăng ký trở thành <strong>Nhà Sáng Tạo (Creator)</strong> trên nền tảng <strong>History Podcast</strong>.</p>
    <p>Mã xác thực OTP của bạn là:</p>
    <div style="text-align: center; margin: 24px 0;">
        <span style="font-size: 32px; font-weight: bold; letter-spacing: 6px; color: #1a1a1a; background-color: #f4f4f4; padding: 12px 24px; border-radius: 6px; display: inline-block;">{{otpCode}}</span>
    </div>
    <p style="color: #666; font-size: 14px;">Mã này có hiệu lực trong <strong>{{expiryMinutes}} phút</strong>. Tuyệt đối không chia sẻ mã này cho bất kỳ ai.</p>
    <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;" />
    <p style="color: #999; font-size: 12px;">Nếu bạn không thực hiện yêu cầu này, vui lòng bỏ qua email.</p>
</div>',
    'Mẫu email gửi mã OTP xác thực hồ sơ KYC Creator',
    'ACTIVE'
)
ON CONFLICT (code) DO NOTHING;
